services:
  postgres:
    image: postgres:17.5
    container_name: microservices-course-2023-postgres
    restart: unless-stopped
    env_file:
      - local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: ${MIGRATOR_IMAGE_NAME:-daniilkalts2006/microservices-course-2023-migrator}:${TAG:-latest}
    build:
      context: .
      dockerfile: migrations/Dockerfile
      target: migrator
    container_name: microservices-course-2023-migrator
    env_file:
      - local.env
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  chat_service:
    image: ${CHAT_SERVICE_IMAGE_NAME:-daniilkalts2006/microservices-course-2023-chat-service}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: chat
    container_name: microservices-course-2023-chat-service
    volumes:
      - ./local.env:/app/local.env
    ports:
      - "50051:50051"
    command: [ "--config-path=/app/local.env" ]
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  user_service:
    image: ${USER_SERVICE_IMAGE_NAME:-daniilkalts2006/microservices-course-2023-user-service}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: user
    container_name: microservices-course-2023-user-service
    volumes:
      - ./local.env:/app/local.env
    ports:
      - "50052:50052"
    command: [ "--config-path=/app/local.env" ]
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

volumes:
  postgres_data: